### PR TITLE
Add a mode to debounced to start executing the function while events are still being received

### PR DESCRIPTION
**Pull request by astrofrog**
This is an attempt to solve https://github.com/glue-viz/glue-jupyter/issues/82, but not quite there yet. For some background, the debounced decorator works fine in master when panning/zooming - the image only updates if the user stops panning for 0.5 seconds. However, for changing e.g. slices, or bias/contrast, I'd like to start getting feedback on the change while I'm dragging the slider, not just when I stop.

I want the calls to happen as fast as possible but at the same time I don't want the image update calls to build up if they are a bit slow, so I'm trying to use/modify ``debounced`` so that the function is guaranteed to execute at regular intervals. The approach here kind of works but for some reason the updates separated by quite a long delay while dragging the slider, and then when I let go, there is still a backlog of calls, so not quite there yet.

To put this a different way, let's say that the image update takes 1 second, I ideally want to see the image update happen every second, and overall, the last update should happen <=1 second from the last event.

@maartenbreddels - does this make sense? Any ideas on how to make this work properly?

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Maybe throttling is a better idea/word:
https://css-tricks.com/debouncing-throttling-explained-examples/#article-header-id-5
Sometimes it's difficult to actually put in words what you want, let alone code.

**Comment by astrofrog** [comment]
Yes, basically what I need is throttling, but rather than having a specific rate of throttling, the rate should essentially be set by the execution time of the function - so that basically we run the function as many times as possible without building up a backlog.

The following example illustrates what I mean with a thread:

```
from threading import Thread
from queue import Queue, Empty

def queue_to_list(q):
    
    # Start off by waiting for an object to be added to the queue
    l = [q.get()]
    
    # Now check if there are any other items in the queue, which we can just do asynchronously
    while True:
        try:
            l.append(q.get_nowait())
        except Empty:
            return l
    

class CallbackHandler(Thread):

    def __init__(self, function):
        super().__init__()
        self.function = function
        self.work_queue = Queue()

    def run(self):

        while True:

            msgs = queue_to_list(self.work_queue)
                    
            if 'stop' in msgs:
                return
            elif len(msgs) > 0:
                area2.value += f'Combining {len(msgs)} messages\n'
                self.function()
                
handler = CallbackHandler(callback)
handler.start()

def add_to_queue(*args):
    area1.value += "Adding to queue\n"
    handler.work_queue.put('run')
    
slider.observe(add_to_queue, 'value')
```

In fact, having thought about this some more, I think threads might indeed be needed for this kind of behavior. I'll see if I can write it up as a decorator.

**Comment by astrofrog** [comment]
Ok so I managed to implement a decorator version of what I need (to opt in to that, the decorator in ``frb_mark.py`` should be changed from ``@debounced`` to ``@thread_throttled(delay=0.1)``. However, there are still issues with the image updating quite slowly while the slider is being changed, and then continuing to update, faster, once the slider stops moving. I think what's happening is actually that the bottleneck must be in the communication between JS and Python. At this point, I'm not sure what the best way is around this.

**Comment by astrofrog** [comment]
I haven't really noticed issues related to this recently, so am just going to close this and consider re-opening if it looks like we need this kind of solution.

**Pull request closed without merging**
