### PR TITLE
Added 'home' tool in bqplot viewers to reset limits

### PR DESCRIPTION
**Pull request by astrofrog**
This works as for the Matplotlib viewers and I think users should be familiar with the icon.

### CODE REVIEW

**Comment by rosteen** [comment]
I confirmed that this works, thanks! We've definitely had a bunch of users/testers requesting this feature. I'm not a big fan of the icon but I think we can override that in Jdaviz if we don't like it, certainly not a blocker here.

**Review by rosteen — APPROVED** [review]

**Comment by astrofrog** [comment]
@rosteen - yes I'm happy to change the icon here too once we have a better option! (might as well be consistent)

**Comment by pllim** [comment]
Thanks! Is there a planned release to include this and recent fixes, or you still waiting for something else?

**Comment by rosteen** [comment]
For what it's worth, we mostly use the material design icons (which are included in ipyvuetify) in Jdaviz. Our UI/UX person designed some custom icons but I don't think we've actually switched to using any of them (whoops).

**Comment by astrofrog** [comment]
@pllim I'll try and do a release on Thursday!

**Comment by astrofrog** [comment]
@pllim - I managed to release v0.4 today: https://pypi.org/project/glue-jupyter/0.4/

**Pull request merged**
