### PR TITLE
Added slicing capabilities to image viewer

### PR DESCRIPTION
**Pull request by astrofrog**
This also fixes a bug in LinkedDropdown related to updating options - I should add a regression test for this.

Fixes https://github.com/glue-viz/glue-jupyter/issues/19

### CODE REVIEW

**Comment by pllim** [comment]
```python
from glue_jupyter.data import require_data
require_data('Astronomy/L1448/l1448_13co.fits')

import glue_jupyter as gj
app = gj.jglue()

cube = app.load_data('l1448_13co.fits')

app.imshow(data=cube)
```

It didn't crash but I don't see the data inside the plot. Also I don't know how to tell it which slice I want.

Screenshot from 2019-04-10 15-57-29

**Comment by astrofrog** [comment]
@pllim - does it never appear even if you try multiple times? I've run into an issue where sometimes the image doesn't appear but sometimes it does, and I haven't quite tracked it down yet.

For the slice, you can select it using the Vopt slider on the right.

**Comment by pllim** [comment]
FWIW I didn't try to run the same cell again and again. I did run the notebook multiple times over different sessions and had zero success.

**Comment by astrofrog** [comment]
Ok no problem, I'll investigate - thanks!

I'm going to close this in favor of #75 since we might as well just merge it all in one go

**Pull request closed without merging**
