### PR TITLE
Add ellipse mode

### LINKED ISSUE #223: Elliptical shape seems allowed in bqplot backend but not really
**Describe the bug**

This implies you support elliptical shape:

https://github.com/glue-viz/glue-jupyter/blob/12f4b2f211f53009dc76b822ba5af7e8db75ebd8/glue_jupyter/bqplot/common/tools.py#L190

But when I use `bqplot:circle` tool over at Jdaviz (Imviz), I can only draw circle.

**Expected behavior**

Not sure what the expectation should be. This is related to spacetelescope/jdaviz#518 , so might need inputs from @eteq et al.

### PR DESCRIPTION
**Pull request by javerbukh**
# Pull Request Template

## Description
This PR attempts to add an EllipticalROI selection tool, which can then be used in jdaviz. It currently uses the `glue_lasso` icon because there is not a `glue_ellipse` icon in glue. 

An alternative to this would be to remove the `pixel_aspect` kwarg in the `BqplotCircleMode` in order to allow ellipses in that mode.

resolves #223

### CODE REVIEW

**Comment by pllim** [comment]
Just curious, does this also fix the shift + drag thingy like with rect/square?

**Comment by javerbukh** [comment]
What is shift + drag supposed to do? For me it locks one axis and lets the other axis move freely to create the shape.

**Review by astrofrog — APPROVED** [review]
This works well - I'll push a commit to master with an updated icon. In future we might want to merge this and the circular tool and indeed use shift to toggle between them but this works fine for now.

**Comment by pllim** [comment]
This might have introduced a lag in interactive region creation. When I downgrade to `glue-jupyter` 0.6, I don't see the lag.

**Comment by pllim** [comment]
Nevermind, I think the actual problem is glue-viz/glue#2138 . Also see https://github.com/spacetelescope/jdaviz/issues/723#issuecomment-876594078

**Pull request merged**
