### PR TITLE
Disable resetting of y_min/y_max in layer artist

### PR DESCRIPTION
**Pull request by astrofrog**
I need to figure out if this code is still needed, but for now it seems it definitely isn't for specviz, so this branch can be used with specviz to avoid rescaling all the time.

### CODE REVIEW

**Comment by pllim** [comment]
If it is somehow needed elsewhere, Jdaviz still need an option to turn it off.

**Comment by pllim** [comment]
I can confirm that this also fixes the issue downstream at spacetelescope/jdaviz#760

**Comment by pllim** [comment]
@camipacifici reported that this might have broken the "Home" button, as pressing Home now does not reset Y-axis zoom in Specviz, though it works fine for Imviz.

**Comment by astrofrog** [comment]
I've updated this to a point where I think I'd be happy to merge. I've also fixed the Home button.

At this point it would be helpful if someone could test this out with jdaviz/specviz though?

cc @camipacifici @pllim

**Comment by rosteen** [comment]
I just confirmed that selecting a subset in the profile viewer no longer resets the y-axis zoom, and that the home button now properly resets both axes again in the profile viewer. Looks good!

**Review by rosteen — APPROVED** [review]

**Comment by pllim** [comment]
I'll have to double check that the markers no longer reset Imviz zoom/pan, unless someone gets to it first.

**Comment by javerbukh** [comment]
When using mosviz, selecting a new row does not change the Y-axis of the spectrum viewer at all. The scale of the first row persists for all the rest, even if the range is much different.

**Comment by pllim** [comment]
My comment at https://github.com/glue-viz/glue-jupyter/pull/247#issuecomment-895271129 is no longer true. This does *not* prevent pan/zoom reset in Imviz no more when markers are added. Not sure what changed.

But the Imviz issue is not important to fix right now.

**Comment by astrofrog** [comment]
This PR never had any impact on the image viewer so I wouldn't expect it to fix your issue @pllim - but if you open a separate issue I can look into it

**Comment by pllim** [comment]
> This PR never had any impact on the image viewer

It did at one point... 😆 

But don't worry about Imviz for now.

**Comment by pllim** [comment]
But since you asked, I did open an issue at spacetelescope/jdaviz#760

**Review by pllim — CHANGES_REQUESTED** [review]
This actually breaks jdaviz... See spacetelescope/jdaviz#874 . Maybe we need this is a very localized section of Jdaviz only...

**Comment by astrofrog** [comment]
I am working on this in https://github.com/glue-viz/glue/pull/2233

**Pull request merged**
