### PR TITLE
FEAT: Annulus draw tool

### PR DESCRIPTION
**Pull request by pllim**
## Description

We need this for Imviz annulus support. This blocks:

* https://github.com/spacetelescope/jdaviz/pull/2240

cc @dhomeier and @astrofrog

### CODE REVIEW

**Comment by pllim** [comment]
p.s. I am not good with the icon stuff, so if you have someone over at Glueviz that makes the proper icons, please feel free to replace the file directly on my branch or open a PR to this PR. Thanks!

**Comment by pllim** [comment]
> icon looks strange

I am not surprised if it looks strange. I don't have time or interest to make pretty icon especially since Jdaviz uses its own icons anyway and we have a professional designer doing that for us. So, if you have a prettier version, please replace the one in this PR.

> I wonder whether after the first click to select, the user should be able to then continue moving the cursor to edit the inner radius?

That could be a follow-up PR. Would be nice to be able to do that at draw time, yes, but I am just not sure what kind of click and when would be the most intuitive, so definitely need some iterations.

**Comment by astrofrog** [comment]
I have fixed the icon:

Screenshot 2023-06-16 at 12 07 45

**Review by astrofrog — APPROVED** [review]
Thanks!

**Pull request merged**
