### PR TITLE
Provide option to reference back to calling app

### PR DESCRIPTION
**Pull request by pllim**
## Description

In Jdaviz, there is no way for the viewer to access the viz app that created it. This PR is needed to remedy that situation.

Needs:

* glue-viz/glue#2256

### CODE REVIEW

**Comment by astrofrog** [comment]
Normally this should be accessible through self.session.application, can you check?

**Comment by pllim** [comment]
I did but that's the JupyterApplication. I need access from viewer to jdaviz.app.Application that's accessible from imviz.app but missing from its viewer instance.

**Comment by astrofrog** [comment]
That seems like a jdaviz-specific thing so not sure it makes sense to implement here, can you not just set .app on the returned instance in jdaviz?

**Comment by pllim** [comment]
I tried that too. It doesn't stick.  I'm not sure why. Maybe overly zealous attribute checks upstream. This is the only way I could make it work without having to do a bunch of stuff to implement backend for viewer specific tray thingies.

**Comment by astrofrog** [comment]
Ok - we have to find a better solution though as other glue-jupyter users won't understand what app is. What if you set session.application.app in jdaviz for instance?

**Comment by pllim** [comment]
That didn't work either. Same problem. It doesn't stick.

**Comment by astrofrog** [comment]
Ohhhh I get it 🤣

**Comment by maartenbreddels** [comment]
I went through the same ideas as @astrofrog , why can't you just set an attribute on session ? like `session.jdaviz = ...` what do you mean by "it doesn't stick" ?

**Comment by pllim** [comment]
I am trying to remember what I did to reach that conclusion. Looks like I tried to do it "properly" by passing `app=...` as part of `**kwargs` that goes into `self._application_handler.new_data_viewer(...)` where `self` is `jdaviz.app.Application`.

But looks like you are suggestion that I simply brute-force it after `viewer` is created. I guess I can give that a try and report back.

**Comment by pllim** [comment]
Nope, doesn't work. See https://github.com/spacetelescope/jdaviz/pull/983/files#r792097008

**Comment by astrofrog** [comment]
Closing in favor of https://github.com/spacetelescope/jdaviz/pull/1051

**Pull request closed without merging**
