### PR TITLE
feat: add multi select mode for ipyvuetify based SubsetSelect 

### PR DESCRIPTION
**Pull request by mariobuikhuizen**

### CODE REVIEW

**Comment by mariobuikhuizen** [comment]
multiselect

**Comment by astrofrog** [comment]
@maartenbreddels - the tests are failing currently as the .vue file needs to be declared in the setup.cfg file (there is already an example for another file/submodule). In addition there are some PEP8 failures. You can run the tests locally with:

```
tox -e py37-test
tox -e pep8
```

**Comment by mariobuikhuizen** [comment]
Thanks!

**Comment by astrofrog** [comment]
Thank you for the PR!

**Pull request merged**
