### PR TITLE
fix: prevent feedback loop when panning in image viewer

### PR DESCRIPTION
**Pull request by mariobuikhuizen**
Capture of the behavior before this fix:
pan

This should fix: https://github.com/spacetelescope/jdaviz/issues/245

### CODE REVIEW

**Comment by maartenbreddels** [comment]
@astrofrog 

We're a bit puzzled by the failure:
```
    super(DeferredDrawCallbackProperty, self).notify(*args, **kwargs)
../../miniconda3/envs/dev/lib/python3.7/site-packages/echo/core.py:125: in notify
    cback(new)
../../miniconda3/envs/dev/lib/python3.7/site-packages/echo/core.py:614: in prop2_from_prop1
    setattr(self.instance2(), self.prop2, getattr(self.instance1(), self.prop1))
../../miniconda3/envs/dev/lib/python3.7/site-packages/echo/core.py:263: in __setattr__
    self._notify_global(**{attribute: value})
../glue/glue/utils/matplotlib.py:165: in wrapper
    return func(*args, **kwargs)
../glue/glue/viewers/matplotlib/state.py:293: in _notify_global
    super(MatplotlibLayerState, self)._notify_global(*args, **kwargs)
../../miniconda3/envs/dev/lib/python3.7/site-packages/echo/core.py:258: in _notify_global
    callback(**kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = None, args = (), kwargs = {'zorder': 2}

    def notify_all(self, *args, **kwargs):
>       for callback in self.callbacks:
E       AttributeError: 'NoneType' object has no attribute 'callbacks'

../../miniconda3/envs/dev/lib/python3.7/site-packages/echo/containers.py:44: AttributeError
```

I think i managed to find the problem underlying this `self is None issue:
```
[11]   /Users/maartenbreddels/src/glue-jupyter/glue_jupyter/bqplot/image/tests/test_viewer.py(18)test_remove()
-> s.add_data(data_volume)
[12]   /Users/maartenbreddels/src/glue-jupyter/glue_jupyter/view.py(117)add_data()
-> result = super().add_data(data)
[13]   /Users/maartenbreddels/src/glue/glue/viewers/common/viewer.py(212)add_data()
-> self._layer_artist_container.append(layer)
[14]   /Users/maartenbreddels/src/glue/glue/core/layer_artist.py(271)append()
-> artist.zorder = max(a.zorder for a in self.artists) + 1
[15]   /Users/maartenbreddels/miniconda3/envs/dev/lib/python3.7/site-packages/echo/core.py(76)__set__()
-> self.notify(instance, old, new)
[16]   /Users/maartenbreddels/src/glue/glue/utils/matplotlib.py(170)wrapper()
-> result = func(*args, **kwargs)
[17]   /Users/maartenbreddels/src/glue/glue/viewers/matplotlib/state.py(24)notify()
-> super(DeferredDrawCallbackProperty, self).notify(*args, **kwargs)
[18]   /Users/maartenbreddels/miniconda3/envs/dev/lib/python3.7/site-packages/echo/core.py(125)notify()
-> cback(new)
[19]   /Users/maartenbreddels/miniconda3/envs/dev/lib/python3.7/site-packages/echo/core.py(614)prop2_from_prop1()
-> setattr(self.instance2(), self.prop2, getattr(self.instance1(), self.prop1))
[20]   /Users/maartenbreddels/miniconda3/envs/dev/lib/python3.7/site-packages/echo/core.py(263)__setattr__()
-> self._notify_global(**{attribute: value})
[21]   /Users/maartenbreddels/src/glue/glue/utils/matplotlib.py(165)wrapper()
-> return func(*args, **kwargs)
[22]   /Users/maartenbreddels/src/glue/glue/viewers/matplotlib/state.py(293)_notify_global()
-> super(MatplotlibLayerState, self)._notify_global(*args, **kwargs)
[23]   /Users/maartenbreddels/miniconda3/envs/dev/lib/python3.7/site-packages/echo/core.py(257)_notify_global()
-> for callback in self._global_callbacks:
[24] > /Users/maartenbreddels/miniconda3/envs/dev/lib/python3.7/site-packages/echo/callback_container.py(74)__iter__()
-> assert inst is not None
(Pdb++) callback
(<weakref at 0x11ea39db8; to 'function' at 0x1117cc7b8 (notify_all)>, <weakref at 0x11f72ce08; dead>, 0)
```

In echo, we have a dead weakref. Maybe you instantly know the cause of this.

**Comment by astrofrog** [comment]
Yeah I'm not 100% sure where the dead weakref happens but I think the most pragmatic solution is to do as in https://github.com/glue-viz/echo/pull/27

**Comment by astrofrog** [comment]
@mariobuikhuizen @maartenbreddels I've just released echo v0.5 which fixes the weakref issue. I think there are some remaining test failures that look real.

**Comment by mariobuikhuizen** [comment]
Thanks! We were already using the PR to run the tests and the remaining failures are indeed real.

**Comment by mariobuikhuizen** [comment]
Turns out this workaround also mitigates the issue previously seen in echo.

**Pull request merged**
