### PR TITLE
Catch DeprecationWarnings by specific filterwarnings / fixes

### PR DESCRIPTION
**Pull request by dhomeier**
## Description

Addressing #237, this replaces the `-Wignore` pytest option from #238 with more specific `filterwarnings` for the `DeprecationWarning` instances and setting `error` for any that would be missed. All but one actually originate from various upstream modules. So unless I am missing some error in usage of those modules all to be followed up on would be reporting the warnings upstream.
And take care of the two in `glue` itself, of course – `astype(np.float)` is straightforward; replacing `imp` could be a bit trickier.
Getting rid of `np.matrix` in the second commit was also trivial since `Projected3dROI` has already cast `projection_matrix` to `asarray` all along.

### CODE REVIEW

**Comment by dhomeier** [comment]
Well, not sure if it's a realistic endeavour to nail down all potential DeprecationWarnings for all combinations of upstream packages/pyver/OS (with new ones likely popping up as soon as a py38 or py39 test is included)...

Now these runtime warnings popped up, which look actually more serious
```
E   RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility. Expected 80 from C header, got 88 from PyObject
- generated xml file: /home/vsts/work/1/s/.tmp/py37-test/junit/test-results.xml -
```
but why only after adding two more `ignores when half of the tests where completing successfully before???

**Comment by dhomeier** [comment]
Beats me why Windows still ignores the `ignore` for the matplotlib deprecation.
I suggest to keep the `RuntimeWarning`s on binary incompatibility visible, although it's not clear to me if or what can be done about them from our side.

**Review by maartenbreddels — APPROVED** [review]

**Comment by maartenbreddels** [comment]
@pllim @astrofrog I wonder if we should merge this, see also #269

**Review by pllim — APPROVED** [review]
Definitely an improvement, though follow-up PRs are needed to reduce the number of ignored warnings.

I don't have write access here, so it is all @astrofrog .

**Comment by maartenbreddels** [comment]
With:
 * https://github.com/jupyter-widgets/pythreejs/pull/368
 * https://github.com/bqplot/bqplot/pull/1406
 * https://github.com/glue-viz/glue/pull/2236
 * https://github.com/maartenbreddels/ipyvolume/pull/390
 
We should actually decrease it in time.

**Review by astrofrog — APPROVED** [review]
I'll go ahead and merge this, but @dhomeier feel free to open a follow-up PR to remove some of the filters that are no longer needed following the 1.2.4 glue-core release (e.g. the imp one and maybe some of the other ones @maartenbreddels mentioned above).

**Pull request merged**
