### PR TITLE
WIP: Use ci-helpers to simplify the conda set-up

### PR DESCRIPTION
**Pull request by astrofrog**
Also switch to codecov for coverage since it produces nicer results

### CODE REVIEW

**Comment by astrofrog** [comment]
Wow conda has got really slow in the last few months...

**Comment by mbargull** [comment]
That `ci-helpers` thingy sets `channel_priority` to `false` which is usually not what you want to do for multiple big channels like `defaults` + `conda-forge`. I fear, you're giving the solver an extra hard time there...
If you can narrow the setup where you observe that bad performance down to a simple `conda create -c channel1 -c channel2 ... packages` which I can run from a clean Miniconda installation, we could track this on the Conda issue tracker.

**Comment by astrofrog** [comment]
@mbargull - thanks for the tip on channel priority! That does seem to help.

**Comment by astrofrog** [comment]
This doesn't un-break the build but it simplifies the Travis config a little. Currently there are real test failures on MacOS X, and there are issues installing ipyvolume on Linux.

**Pull request merged**
