### PR TITLE
BUG: Only recast float if image is not None

### PR DESCRIPTION
**Pull request by pllim**
This is a direct follow-up of #318 . Without this patch dev job is failing at Jdaviz.

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Thanks. I wonder if it makes sense to run the jdaviz test suite here.

**Comment by pllim** [comment]
> run the jdaviz test suite here

Hmm. Maybe @astrofrog has ideas for proper integration testing.

In the meantime, that is what the dev deps job in Jdaviz is for. 😸

**Comment by dhomeier** [comment]
Thanks! I assume that is the only case where `image` might not have a `dtype`?

**Comment by dhomeier** [comment]
> In the meantime, that is what the dev deps job in Jdaviz is for. 😸

Would still be helpful to have tests that can be run in an open PR here.

**Comment by pllim** [comment]
I looked at the line changed here and it is not obvious to me what kind of test would actually trigger that line. There is no documentation. So I'll leave it to the experts to add a test. Thanks!

https://github.com/glue-viz/glue-jupyter/blob/ba222b6a9f6848f0ef4b6e1ff122825d95561044/glue_jupyter/bqplot/image/frb_mark.py#L18-L20

**Pull request merged**
